# Enable mouse emulation.
# CONFIG_ZMK_POINTING=y
# CONFIG_ZMK_POINTING_SMOOTH_SCROLLING=y

# Enable USB support in BIOS/UEFI and pre-boot environments.
# CONFIG_ZMK_USB_BOOT=y

# Change idle settings
# CONFIG_ZMK_IDLE_TIMEOUT=30000

# RGB underglow
CONFIG_ZMK_RGB_UNDERGLOW_ON_START=y
CONFIG_ZMK_RGB_UNDERGLOW_AUTO_OFF_IDLE=y
CONFIG_ZMK_RGB_UNDERGLOW_BRT_STEP=5
CONFIG_ZMK_RGB_UNDERGLOW_BRT_START=20
CONFIG_ZMK_RGB_UNDERGLOW_HUE_START=200
CONFIG_ZMK_RGB_UNDERGLOW_SAT_START=98

# Keep the display active while the keyboard is idle
CONFIG_ZMK_DISPLAY_BLANK_ON_IDLE=n

# Enter deep sleep after one hour of inactivity
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=3600000

# Custom keyboard name (max. 16 characters)
CONFIG_ZMK_KEYBOARD_NAME="Piantor Pro BT"
